spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-dawn-scene-an2ndwp1-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
